language: node_js
env:
  - NODE_ENV: src:src/hooks:src/pages:src/containers:src/images:src/data:src/styled
node_js:
  - 'stable'
install:
  - npm install
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
