language: node_js
env:
  - NODE_ENV: src:src/hooks:src/pages:src/containers:src/images:src/data:src/styled
node_js:
  - 'stable'
install:
  - yarn install
script:
  - yarn build
  - yarn test
cache:
  directories:
    - node_modules
